### ISSUE TITLE
There is no way to authenticate with stash if username and password are present

### ISSUE THREAD

**Issue by spiritedusual** [Schmoaaaaah/yt-dlp-stash#1]
I do not see a way to include an api key or provide any authentication for Stash is a login and password are set. 

There is stash documentation to do this, but my knowledge of these things is limited. Please advise. 

https://docs.stashapp.cc/networking/api/

**Comment by schmoaaaaah** [comment]
Yeah i havent implemented any form of authentication as i havent needed it in my case, but i will look into it on the weekend.

**Comment by spiritedusual** [comment]
Thank you so much. I did turn off authentication to get it to work, and it
does work really really well btw. Getting authentication would be the
cherry on top.

Thank you again.

**Comment by schmoaaaaah** [comment]
The library that i use actually supports authentication so it was easier then expected.
I created a [branch](https://github.com/Schmoaaaaah/yt-dlp-stash/tree/add-auth-option) with it.
Would you mind trying if that works?

**Comment by spiritedusual** [comment]
Thank you! Looks like that did it. I added my API key to the top and all is
well. I'm not familiar with pip or github, and the instructions for the
master did not work for the branch, but I assume this is normal behaviour.
In the end I had to move the file manually.

Thank you again.

**Comment by schmoaaaaah** [comment]
That sounds good.
I merged it into master so the Readme instructions should work now.
alternatively you can also get it on [PyPi](https://pypi.org/project/yt-dlp-stash/).
